apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
  namespace: community
  labels:
    app: community-service
    project: SecN3t
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community-service
      project: SecN3t
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: community-service
        project: SecN3t
        tier: backend
    spec:
      containers:
      - name: community-service
        image: nginx:alpine
        ports:
        - containerPort: 80
