apiVersion: v1
kind: Pod
metadata:
  name: community-service
  namespace: community
  labels:
    app: community-service
    project: cybernest
    tier: backend
spec:
  containers:
  - name: community-service
    image: nginx:alpine
    ports:
    - containerPort: 80
