apiVersion: v1
kind: Pod
metadata:
  name: monitoring-service
  namespace: monitoring
  labels:
    app: monitoring-service
    project: cybernest
    tier: backend
spec:
  containers:
  - name: monitoring-service
    image: nginx:alpine
    ports:
    - containerPort: 80
